{% set name = "pypeit" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2a7082cd905dec2713dc53b0382a1f02a26ca115d451bff58c1e92bb4bca6d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - extension-helpers >=0.1
    - setuptools_scm >=5
  run:
    - python
    - numpy >=1.18
    - astropy >=4.0
    - scipy >=1.4
    - matplotlib-base >=3.1
    - numba >=0.39.0
    - qtpy >=1.9
    - pyyaml >=5.1
    - configobj >=5.0.6
    - scikit-learn >=0.20
    - ipython >=7.2.0
    - ginga >=3.0
    - packaging >=19.0
    - linetools >=0.3.dev2231
    - extension-helpers >=0.1
    - shapely >=1.7.1
    - requests >=2.23

test:
  requires:
    - pytest
  imports:
    - pypeit
  commands:
    - run_pypeit -h
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/pypeit/PypeIt
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.rst
    - licenses/PYDL_LICENSE.rst
  summary: The Python Spectroscopic Data Reduction Pipeline.

  description: |
    PypeIt is a Python package for semi-automated reduction of astronomical,
    spectroscopic data. Its algorithms build on decades-long development of
    previous data reduction pipelines by the developers. PypeIt is a set of
    commands designed to perform the reduction without any additional coding.
  doc_url: https://pypeit.readthedocs.io/
  dev_url: https://github.com/pypeit/PypeIt

extra:
  recipe-maintainers:
    - finagle29
